version: '3'

services:

  fastapi:
    container_name: fastapi
    build: ./fastapi_app
    volumes:
      - ./fastapi_app:/fastapi_app
#    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: poetry run uvicorn main:app --reload --host 0.0.0.0
    depends_on:
      - neo4j

  ui:
    container_name: web_ui
    build: ./UI/web_ui
    volumes:
      - ./UI/web_ui:/UI/web_ui
    ports:
      - "3000:3000"
    environment:
      DEBUG: 'true'
    command: npm start
    depends_on:
      - fastapi

  neo4j:
    restart: always
    image: neo4j:4.2.3
    container_name: neo4j
    networks:
      default:
        aliases:
         - neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./course_work_5_sem:/course_work_5_sem
    environment:
      - NEO4J_AUTH=neo4j/cooking
